version: '3.9'

services:
  theia-base-310:
    image: registry.digitalocean.com/anubis/theia-base:python-3.10
    ports:
      - "5000:5000"
    build:
      context: ./theia-base
      args:
        PY_VERSION: '3.10.6'
        BUILD_THEIA: 'ON'
  theia-base-311:
    image: registry.digitalocean.com/anubis/theia-base:python-3.11
    ports:
      - "5000:5000"
    build:
      context: ./theia-base
      args:
        PY_VERSION: '3.11.13'
        BUILD_THEIA: 'ON'
  theia-base-312:
    image: registry.digitalocean.com/anubis/theia-base:python-3.12
    ports:
      - "5000:5000"
    build:
      context: ./theia-base
      args:
        PY_VERSION: '3.12.11'
        BUILD_THEIA: 'ON'
  theia-base-313:
    image: registry.digitalocean.com/anubis/theia-base:python-3.13
    ports:
      - "5000:5000"
    build:
      context: ./theia-base
      args:
        PY_VERSION: '3.13.7'
        BUILD_THEIA: 'ON'
  ## Webtop base images
  webtop-base-310:
    image: registry.digitalocean.com/anubis/webtop-base:python-3.10
    ports:
      - "5000:5000"
    build:
      context: ./theia-base
      dockerfile: Dockerfile-webtop
      args:
        PY_VERSION: '3.10.6'
  webtop-base-311:
    image: registry.digitalocean.com/anubis/webtop-base:python-3.11
    ports:
      - "5000:5000"
    build:
      context: ./theia-base
      dockerfile: Dockerfile-webtop
      args:
        PY_VERSION: '3.11.13'
  webtop-base-312:
    image: registry.digitalocean.com/anubis/webtop-base:python-3.12
    ports:
      - "5000:5000"
    build:
      context: ./theia-base
      dockerfile: Dockerfile-webtop
      args:
        PY_VERSION: '3.12.11'
  webtop-base-313:
    image: registry.digitalocean.com/anubis/webtop-base:python-3.13
    ports:
      - "5000:5000"
    build:
      context: ./theia-base
      dockerfile: Dockerfile-webtop
      args:
        PY_VERSION: '3.13.7'

  ## General IDE images
  theia-golang:
    image: registry.digitalocean.com/anubis/theia-golang:latest
    ports:
      - "5000:5000"
    build: ./theia-golang

  theia-cpp:
    image: registry.digitalocean.com/anubis/theia-cpp:latest
    ports:
      - "5000:5000"
    build: ./theia-cpp

  theia-procdesign:
    image: registry.digitalocean.com/anubis/theia-procdesign:latest
    ports:
      - "5000:5000"
    build: ./theia-procdesign

  theia-admin:
    image: registry.digitalocean.com/anubis/theia-admin:latest
    ports:
      - "5000:5000"
    build: ./theia-admin

  theia-flask-310:
    image: registry.digitalocean.com/anubis/theia-flask:python-3.10
    ports:
      - "5000:5000"
    build:
      context: ./theia-flask
      args:
        PY_VERSION: '3.10'

  theia-mysql-310:
    image: registry.digitalocean.com/anubis/theia-mysql:python-3.10
    ports:
      - "5000:5000"
    build:
      context: ./theia-mysql
      args:
        PY_VERSION: '3.10'

  ## Course specific images
  # Image for devops with Calahan
  theia-devops:
    image: registry.digitalocean.com/anubis/theia-devops:latest
    ports:
      - "5000:5000"
    build: ./theia-devops

  ## Course specific images
  # Image for OSIRIS
  theia-osiris:
    image: registry.digitalocean.com/anubis/theia-osiris:latest
    ports:
      - "5000:5000"
    build: ./theia-osiris
  
  webtop-osiris:
    image: registry.digitalocean.com/anubis/webtop-osiris:latest
    user: root
    ports:
      - "5000:5000"
    build:
      context: ./theia-osiris
      args:
        PY_VERSION: '3.10'
        WEBTOP: 'ON'
        BASE_IMAGE: registry.digitalocean.com/anubis/webtop-base:python-3.10

  ## Course specific images
  # Image for OSIRIS
  theia-pincer:
    image: registry.digitalocean.com/anubis/theia-pincer:latest
    ports:
      - "5000:5000"
    build: ./theia-pincer

  # Image for CompArch & PL with Epstein
  theia-jepst:
    image: registry.digitalocean.com/anubis/theia-jepst:latest
    ports:
      - "5000:5000"
    build:
      context: ./theia-jepst
      args:
        PY_VERSION: '3.10'
        WEBTOP: 'OFF'
  webtop-jepst:
    image: registry.digitalocean.com/anubis/webtop-jepst:latest
    ports:
      - "5000:5000"
    build:
      context: ./theia-jepst
      args:
        PY_VERSION: '3.10'
        WEBTOP: 'ON'
        BASE_IMAGE: registry.digitalocean.com/anubis/webtop-base:python-3.10
