#!/bin/bash

if [ ! -e /lock.file ]; then
  # give anubis a sudo shell
#  chsh anubis -s /bin/bash
#  sed -e 's/%sudo	ALL=(ALL:ALL) ALL/%sudo ALL=(ALL:ALL) NOPASSWD: ALL/g' \
#      -i /etc/sudoers
  sed -e 's/^wheel:\(.*\)/wheel:\1,anubis/g' -i /etc/group
fi

# create lock file after first run
touch /lock.file

# default file copies first run
[[ ! -d /home/anubis/.config ]] && mkdir -p /home/anubis/.config
[[ ! -d /home/anubis/Desktop ]] && mkdir -p /home/anubis/Desktop
cp /usr/share/applications/code.desktop /home/anubis/Desktop/

# permissions
PERM=$(stat -c '%U' /home/anubis/.config)
[[ "${PERM}" != "anubis" ]] && \
        chown -R anubis:anubis /home/anubis

chown -R ${PUID}:${GUID} /home/anubis


