#!/bin/bash

if [ ! -e /lock.file ]; then
  # give abc a sudo shell
#  chsh abc -s /bin/bash
#  sed -e 's/%sudo	ALL=(ALL:ALL) ALL/%sudo ALL=(ALL:ALL) NOPASSWD: ALL/g' \
#      -i /etc/sudoers
  sed -e 's/^wheel:\(.*\)/wheel:\1,abc/g' -i /etc/group
fi

# create lock file after first run
touch /lock.file

# default file copies first run
[[ ! -d /home/anubis/.config ]] && \
	mkdir -p /home/anubis/.config

mkdir -p /home/anubis/.config/xfce4/launcher-21/
cp /usr/share/applications/code.desktop /home/anubis/.config/xfce4/launcher-21/

# permissions
PERM=$(stat -c '%U' /home/anubis/.config)
[[ "${PERM}" != "abc" ]] && \
        chown -R abc:abc /home/anubis

chown -R ${PUID}:${GUID} /home/anubis


